EE_LIBS = -luyapal
EE_OBJS = main.o
EE_ELF = alpine-junction-10683.elf
EE_BIN = alpine-junction-10683.bin
EE_DEFS += -DUYA_PAL

CODE_BIN = pal
CODE_ADDR = 0054D5F0
CODE_ENTRY = 00443448

include ${CURDIR}/Makefile.base
