#include <libuya/interop.h>

VariableAddress_t vaWeaponPackSpawnFunc;
VariableAddress_t vaRespawnTimerFunc;
VariableAddress_t vaSpawnWeaponPackFunc;
VariableAddress_t vaRespawnTimerHook;
VariableAddress_t vaCheckWeaponKill;
VariableAddress_t vaUpdateWeaponKill;
VariableAddress_t vaDM_PressXToRespawn;
VariableAddress_t vaNodeTurret_UpdateFunc;
VariableAddress_t vaCameraShakeFunc;
VariableAddress_t vaDM_RespawnUpdater;
VariableAddress_t vaRespawnTimerFunc_Player;
VariableAddress_t vaPostHitInvinc;
VariableAddress_t vaHealthbars_Hook;
VariableAddress_t vaRadarBlips_FloatVal;
VariableAddress_t vaPlayerInvincibleTimer_Hook;
VariableAddress_t vaPlayerInvincibleTimer_Func;
